version: 3,
services:
  nodejs-server:
    image: nadavribak/posts-server
    environment:
      MONGO_CONNECTION_URI: mongodb://nodejs-mongo:27017/nodejs-kubernetes
      REDIS_HOST: nodejs-redis
      REDIS_PORT: 6379
      PORT: 4000
      REDIS_EXPIRE: 3600
    depends_on:
      - nodejs-mongo
      - nodejs-redis
  nodejs-mongo:
    image: mongo:latest
  nodejs-redis:
    image: redis:latest
  nodejs-next-client:
    image: nadavribak/posts-client
    ports:
      - 80:3000
    environment:
      POSTS_SERVICE_URI: nodejs-server

